## Part 1: Preprocessing

In [24]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from sklearn.preprocessing import OneHotEncoder


#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [25]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [26]:
# Create y_df with the Attrition and Department columns

y_df = attrition_df[['Attrition', 'Department']]

y_df.head()

  Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [27]:
department_y_df = y_df['Department']
attrition_y_df = y_df['Attrition']

print(f"Department y_df shape: {department_y_df.shape}")
print(f"Attrition y_df shape: {attrition_y_df.shape}")

Department y_df shape: (1470,)
Attrition y_df shape: (1470,)

In [28]:
# Create a list of at least 10 column names to use as X data

column_names = ['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime', 'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany', 'YearsSinceLastPromotion', 'NumCompaniesWorked']

# Create X_df using your selected columns

X_df = attrition_df[column_names]

# Show the data types for X_df

X_df.dtypes

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [29]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)

In [30]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

X_train = pd.get_dummies(X_train)

X_test = pd.get_dummies(X_test)

X_train.dtypes

Education                  int64
Age                        int64
DistanceFromHome           int64
JobSatisfaction            int64
StockOptionLevel           int64
WorkLifeBalance            int64
YearsAtCompany             int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
OverTime_No                 bool
OverTime_Yes                bool
dtype: object

In [31]:
from re import X
# Create a StandardScaler

scaler = StandardScaler()

# Fit the StandardScaler to the training data

X_scaler = scaler.fit(X_train)

# Scale the training and testing data

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

X_train_scaled.shape

(1102, 11)

In [32]:
# Create a OneHotEncoder for the Department column

enc_department = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data

enc_department.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data

department_y_train_encoded = enc_department.transform(y_train[['Department']])

department_y_test_encoded = enc_department.transform(y_test[['Department']])

department_y_train_encoded.shape

(1102, 3)

In [33]:
# Create a OneHotEncoder for the Attrition column

enc_attrition = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data

enc_attrition.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data

attrition_y_train_encoded = enc_attrition.transform(y_train[['Attrition']])

attrition_y_test_encoded = enc_attrition.transform(y_test[['Attrition']])

attrition_y_train_encoded.shape

(1102, 2)

In [34]:
print(f"Department y_train_encoded shape: {department_y_train_encoded.shape}")
print(f"Attrition y_train_encoded shape: {attrition_y_train_encoded.shape}")

Department y_train_encoded shape: (1102, 3)
Attrition y_train_encoded shape: (1102, 2)

## Create, Compile, and Train the Model

In [35]:
# Find the number of columns in the X training data

num_columns = X_train_scaled.shape[1]

# Create the input layer

input_layer = layers.Input(shape=(num_columns,))

# Create at least two shared layers

shared_layer1 = layers.Dense(units=128, activation='relu')(input_layer)

shared_layer2 = layers.Dense(units=64, activation='relu')(shared_layer1)

In [36]:
# Create a branch for Department
# with a hidden layer and an output layer

department_branch = layers.Dense(units=32, activation='relu')(shared_layer2)

# Create the hidden layer

hidden_layer1 = layers.Dense(units=64, activation='relu')(department_branch)

# Create the output layer

output_layer1 = layers.Dense(units=department_y_train_encoded.shape[1], activation='softmax', name='department_output')(hidden_layer1)

In [37]:
# Create a branch for Attrition
# with a hidden layer and an output layer

attrition_branch = layers.Dense(units=32, activation='relu')(shared_layer2)

# Create the hidden layer

hidden_layer2 = layers.Dense(units=64, activation='relu')(attrition_branch)

# Create the output layer

output_layer2 = layers.Dense(units=attrition_y_train_encoded.shape[1], activation='softmax', name='attrition_output')(hidden_layer2)

In [38]:
# Create the model

model = Model(inputs=input_layer, outputs=[output_layer1, output_layer2])

# Compile the model

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Summarize the model

model.summary()

print(f"X_train_scaled shape: {X_train_scaled.shape}")
print(f"Department y_train_encoded shape: {department_y_train_encoded.shape}")
print(f"Attrition y_train_encoded shape: {attrition_y_train_encoded.shape}")

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_2 (InputLayer)        [(None, 11)]                 0         []

 dense_6 (Dense)             (None, 128)                  1536      ['input_2[0][0]']

 dense_7 (Dense)             (None, 64)                   8256      ['dense_6[0][0]']

 dense_8 (Dense)             (None, 32)                   2080      ['dense_7[0][0]']

 dense_10 (Dense)            (None, 32)                   2080      ['dense_7[0][0]']

 dense_9 (Dense)             (None, 64)                   2112      ['dense_8[0][0]']

 dense_11 (Dense)            (None, 64)                   2112      ['dense_10[0][0]']

 department_output (Dense)   (None, 3)                    195       ['dense_9[0][0]']

 attrition_output (Dense)    (None, 2)                    130       ['dense_11[0][0]']

==================================================================================================
Total params: 18501 (72.27 KB)
Trainable params: 18501 (72.27 KB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________
X_train_scaled shape: (1102, 11)
Department y_train_encoded shape: (1102, 3)
Attrition y_train_encoded shape: (1102, 2)

In [39]:
# Train the model

model.fit(X_train_scaled, [department_y_train_encoded, attrition_y_train_encoded], epochs=10, batch_size=32)

Epoch 1/10
35/35 [==============================] - 2s 3ms/step - loss: 1.4114 - department_output_loss: 0.8749 - attrition_output_loss: 0.5365 - department_output_accuracy: 0.6152 - attrition_output_accuracy: 0.7405
Epoch 2/10
35/35 [==============================] - 0s 3ms/step - loss: 1.1741 - department_output_loss: 0.7805 - attrition_output_loss: 0.3935 - department_output_accuracy: 0.6579 - attrition_output_accuracy: 0.8466
Epoch 3/10
35/35 [==============================] - 0s 4ms/step - loss: 1.1386 - department_output_loss: 0.7659 - attrition_output_loss: 0.3727 - department_output_accuracy: 0.6579 - attrition_output_accuracy: 0.8466
Epoch 4/10
35/35 [==============================] - 0s 3ms/step - loss: 1.1144 - department_output_loss: 0.7626 - attrition_output_loss: 0.3518 - department_output_accuracy: 0.6588 - attrition_output_accuracy: 0.8530
Epoch 5/10
35/35 [==============================] - 0s 3ms/step - loss: 1.0819 - department_output_loss: 0.7464 - attrition_output_loss: 0.3354 - department_output_accuracy: 0.6561 - attrition_output_accuracy: 0.8702
Epoch 6/10
35/35 [==============================] - 0s 3ms/step - loss: 1.0598 - department_output_loss: 0.7366 - attrition_output_loss: 0.3232 - department_output_accuracy: 0.6624 - attrition_output_accuracy: 0.8739
Epoch 7/10
35/35 [==============================] - 0s 3ms/step - loss: 1.0393 - department_output_loss: 0.7284 - attrition_output_loss: 0.3109 - department_output_accuracy: 0.6606 - attrition_output_accuracy: 0.8811
Epoch 8/10
35/35 [==============================] - 0s 3ms/step - loss: 1.0199 - department_output_loss: 0.7137 - attrition_output_loss: 0.3062 - department_output_accuracy: 0.6615 - attrition_output_accuracy: 0.8875
Epoch 9/10
35/35 [==============================] - 0s 3ms/step - loss: 0.9852 - department_output_loss: 0.6943 - attrition_output_loss: 0.2909 - department_output_accuracy: 0.6887 - attrition_output_accuracy: 0.8920
Epoch 10/10
35/35 [==============================] - 0s 5ms/step - loss: 0.9810 - department_output_loss: 0.6899 - attrition_output_loss: 0.2912 - department_output_accuracy: 0.6788 - attrition_output_accuracy: 0.8838

In [40]:
# Evaluate the model with the testing data

evaluation = model.evaluate(X_test_scaled, [department_y_test_encoded, attrition_y_test_encoded])

12/12 [==============================] - 0s 2ms/step - loss: 1.2574 - department_output_loss: 0.8343 - attrition_output_loss: 0.4231 - department_output_accuracy: 0.5598 - attrition_output_accuracy: 0.8424

In [41]:
# Print the accuracy for both department and attrition

print(f"Accuracy for Department output: {evaluation[3]}")
print(f"Accuracy for Attrition output: {evaluation[4]}")

Accuracy for Department output: 0.5597826242446899
Accuracy for Attrition output: 0.842391312122345

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. No. For this dataset it would be better to look at metrics like prescision, recall, and F1 scores or a confusion matrix. These metrics would help to understand how the model was performing on the data rather than just its percentage accuracy.

2. I chose the 'softmax' activation function because it handles multiclass classification problems well. This is useful since the 'department', and 'attrition' columns both involve classifications into multiple categories.

3. Create new features from the data that might better model the patterns in the data. Hyperparameter tuning like grid search or random search. Cross-validation to better understand the models performances so that further adjustments could be made.